### ISSUE TITLE
Suggest adding a build/deploy step in the workflow, before the test

### ISSUE THREAD

**Issue by nhoizey** [WPO-Foundation/webpagetest-github-action#1]
Reading the README of this action, it looks like the provided code does a checkout and then runs the test.

I know there are many ways to deploy a site, but I think you could at least mention that this is a required step in the workflow, to make sure the test is done on the new code instead of the previous one already deployed.

Refusing a new PR because the previous one (that was accepted) was not good with the performance budget might lead to some tension in development teams… 😅

**Comment by tkadlec** [comment]
Heh. Yeah, I meant to add a few examples for this, but I can absolutely clarify.

FWIW, the checkout is just to get access to the latest commit info. The test that gets run is entirely independent of that. So...to make this particularly useful, the URL's you provide need to be deploy previews, etc. 

I'll make that clear and add an example of how you can do this with Netlify, just to help folks see the potential process.

**Comment by nhoizey** [comment]
@tkadlec great, thanks! 👍

**Comment by tkadlec** [comment]
Something kinda cool here in the works, but for now, does this help? https://github.com/WPO-Foundation/webpagetest-github-action#testing-against-a-deployment-url

**Comment by nhoizey** [comment]
@tkadlec this is perfect!

**Comment by gloompi** [comment]
@tkadlec how can we wait for heroku buld? I can't find any library like wait-for-heroku-action
