### ISSUE TITLE
how can I get the source code of the WebPageTest

### ISSUE THREAD

**Issue by weiyan-shi** [WPO-Foundation/webpagetest-github-action#18]
Dear developers, hello, I want to study the paint events of web pages recently, so I want to see how you get them, is it convenient to open source.

**Comment by stoyan** [comment]
https://github.com/WPO-Foundation/webpagetest is the test creation and getting results
https://github.com/WPO-Foundation/wptagent is how we talk to browsers and execute the tests

**Comment by weiyan-shi** [comment]
thanks.
