### ISSUE TITLE
"not found" error when attempting to apply mime-type budget on scripted run

### ISSUE THREAD

**Issue by bhattchaitanya** [WPO-Foundation/webpagetest-github-action#2]
We have a scripted webpagetest. When we pass the script to "runtest" function, webpagetest executes the script properly and returns the result. But the collectData() func errors out with "ERR_ASSERTION" `not found`. in result object, run 'x' JSON object has the breakdown MIME-type but the webpagetest library does not seem to find it.
This issue strangely happens only for a scripted runs and not when URLs are explicitly passed.

**Comment by tkadlec** [comment]
Funky!

What commands are you using in the script itself? (if you're able to post the script with any sensitive info replaced with placeholders, that would be super helpful for debugging)

**Comment by bhattchaitanya** [comment]
closed figured the root cause of the issue. 
just realized that in a scripted run, there are no median values for mime-type breakdowns. Only URL based tests have median values have them.
This is probably because, scripted runs have multiple steps where each step is potentially launching new URLs or downloading new resources.
